eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
        
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
    
server:
  port: 8090
spring:
  cloud:
    stream:
      bindings:
        output:
            destination:  ordUpdateTopic
            content-type: application/json
      kafka:
        binder:
          zkNodes: 13.67.219.107:2181
          brokers: 13.67.219.107:2181